export const env = import.meta.env;

export const BASENAME = env.VITE_BASENAME;

export const SERVER_ADRESS = env.VITE_SERVER_ADRESS;
export const SERVER_LOGIN_ADRESS = env.VITE_SERVER_LOGIN_ADRESS;
export const SERVER_LOGOUT_ADRESS = env.VITE_SERVER_LOGOUT_ADRESS;
export const SERVER_REGISTER_ADRESS = env.VITE_SERVER_REGISTER_ADRESS;
export const SERVER_CREATE_PATH_ADRESS = env.VITE_SERVER_CREATE_PATH_ADRESS;
export const SERVER_GET_STAT_ADRESS = env.VITE_SERVER_GET_STAT_ADRESS;
export const SERVER_GET_ALL_PATHS_ADRESS = env.VITE_SERVER_GET_ALL_PATHS_ADRESS;
export const SERVER_CHECK_AUTH_ADRESS = env.VITE_SERVER_CHECK_AUTH_ADRESS;
