export const env = import.meta.env;

export const SERVER_ADRESS = env.VITE_SERVER_ADRESS;

// auth
export const SERVER_AUTH_ADRESS = env.VITE_SERVER_AUTH_ADRESS;
export const SERVER_LOGIN_ADRESS = env.VITE_SERVER_LOGIN_ADRESS;
export const SERVER_LOGOUT_ADRESS = env.VITE_SERVER_LOGOUT_ADRESS;
export const SERVER_REGISTER_ADRESS = env.VITE_SERVER_REGISTER_ADRESS;

//  refrash jwt
export const SERVER_REFRASH_ADRESS = env.VITE_SERVER_REFRASH_ADRESS;

//  profile
export const SERVER_PROFILE_ADRESS = env.VITE_SERVER_PROFILE_ADRESS;

//  person
export const SERVER_PERSON_ADRESS = env.VITE_SERVER_PERSON_ADRESS;

//  user
export const SERVER_USER_ADRESS = env.VITE_SERVER_USER_ADRESS;

//  relation
export const SERVER_RELATION_ADRESS = env.VITE_SERVER_RELATION_ADRESS;

//  types of relations
export const SERVER_TYPES_OF_RELATIONS_ADRESS = env.VITE_SERVER_TYPES_OF_RELATIONS_ADRESS;

//  tree
export const SERVER_TREE_ADRESS = env.VITE_SERVER_TREE_ADRESS;

// license
export const LICENSE_ADRESS = env.VITE_LICENSE_ADRESS;
